import axios from 'axios';
import { companies, users } from '../../models';
import { getTablesOrder } from './get-dependency-map';

jest.mock('axios');

const metadata = {
  data: {
    account_type: {
      fields: [
        {
          field_type: 'text',
          display_name: 'Account Type',
          primary_key: false,
          required: false,
          workflow: true,
          filter: true,
          search: false,
          export: true,
          import: true,
          inheritance: true,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            filter_field_type: 'text',
            prefix: 'account_type',
          },
          search_config: {},
          export_config: {},
          import_config: {},
          field_name: 'account_type',
        },
        {
          field_type: 'text',
          display_name: 'Sub Types',
          primary_key: false,
          required: false,
          workflow: true,
          filter: true,
          search: false,
          export: true,
          import: true,
          inheritance: true,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            filter_field_type: 'text',
            prefix: 'account_type',
          },
          search_config: {},
          export_config: {},
          import_config: {},
          field_name: 'sub_types',
        },
        {
          field_type: 'text',
          display_name: 'Created By',
          primary_key: false,
          required: false,
          workflow: false,
          filter: true,
          search: false,
          export: true,
          import: false,
          inheritance: false,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            filter_field_type: 'text',
            prefix: 'account_type',
          },
          search_config: {},
          export_config: {},
          import_config: {},
          field_name: 'created_by',
        },
        {
          field_type: 'text',
          display_name: 'Updated By',
          primary_key: false,
          required: false,
          workflow: false,
          filter: true,
          search: false,
          export: true,
          import: false,
          inheritance: false,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            filter_field_type: 'text',
            prefix: 'account_type',
          },
          search_config: {},
          export_config: {},
          import_config: {},
          field_name: 'updated_by',
        },
        {
          field_type: 'date',
          display_name: 'Created Date',
          primary_key: false,
          required: false,
          workflow: false,
          filter: true,
          search: false,
          export: true,
          import: false,
          inheritance: false,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            prefix: 'customer',
            filter_field_type: 'date',
          },
          search_config: {},
          export_config: {},
          import_config: {
            sample_value: '12/20/2020',
          },
          field_name: 'created_date',
        },
        {
          field_type: 'date',
          display_name: 'Updated Date',
          primary_key: false,
          required: false,
          workflow: false,
          filter: true,
          search: false,
          export: true,
          import: false,
          inheritance: false,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            prefix: 'customer',
            filter_field_type: 'date',
          },
          search_config: {},
          export_config: {},
          import_config: {
            sample_value: '12/20/2020',
          },
          field_name: 'updated_date',
        },
      ],
      version: 1,
      is_auto_check: false,
      description: '',
      associations: undefined,
      filter_associations: ['account_type'],
      actions: {
        create: {
          workflow: true,
          label: 'Create Record',
        },
        edit: {
          workflow: true,
          label: 'Update Record',
        },
        remove: {
          workflow: true,
          label: 'Delete Record',
        },
      },
    },
    chart_of_account: {
      fields: [
        {
          field_type: 'text',
          display_name: 'Code',
          primary_key: false,
          required: false,
          workflow: true,
          filter: true,
          search: false,
          export: true,
          import: true,
          inheritance: true,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            filter_field_type: 'text',
            prefix: 'chart_of_account',
          },
          search_config: {},
          export_config: {},
          import_config: {},
          field_name: 'code',
        },
        {
          field_type: 'text',
          display_name: 'Name',
          primary_key: false,
          required: false,
          workflow: true,
          filter: true,
          search: false,
          export: true,
          import: true,
          inheritance: true,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            filter_field_type: 'text',
            prefix: 'chart_of_account',
          },
          search_config: {},
          export_config: {},
          import_config: {},
          field_name: 'name',
        },
        {
          field_type: 'text',
          display_name: 'Account Type',
          primary_key: false,
          required: false,
          workflow: true,
          filter: true,
          search: false,
          export: true,
          import: true,
          inheritance: true,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            filter_field_type: 'text',
            prefix: 'chart_of_account',
          },
          search_config: {},
          export_config: {},
          import_config: {},
          field_name: 'account_type',
        },
        {
          field_type: 'text',
          display_name: 'Account Sub Type',
          primary_key: false,
          required: false,
          workflow: true,
          filter: true,
          search: false,
          export: true,
          import: true,
          inheritance: true,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            filter_field_type: 'text',
            prefix: 'chart_of_account',
          },
          search_config: {},
          export_config: {},
          import_config: {},
          field_name: 'sub_type',
          db_name: 'account_sub_type',
        },
        {
          field_type: 'text',
          display_name: 'Description',
          primary_key: false,
          required: false,
          workflow: true,
          filter: true,
          search: false,
          export: true,
          import: true,
          inheritance: true,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            filter_field_type: 'text',
            prefix: 'chart_of_account',
          },
          search_config: {},
          export_config: {},
          import_config: {},
          field_name: 'description',
        },
        {
          field_type: 'number',
          display_name: 'Balance',
          primary_key: false,
          required: false,
          workflow: false,
          filter: true,
          search: false,
          export: true,
          import: true,
          inheritance: true,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            filter_field_type: 'number',
            prefix: 'chart_of_account',
          },
          search_config: {},
          export_config: {},
          import_config: {},
          field_name: 'balance',
        },
        {
          field_type: 'boolean',
          display_name: 'Status',
          primary_key: false,
          required: false,
          workflow: true,
          filter: true,
          search: false,
          export: true,
          import: true,
          inheritance: true,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [
            {
              value: true,
              label: 'Yes',
              default: true,
            },
            {
              value: false,
              label: 'No',
            },
          ],
          validations: {},
          filter_config: {
            filter_field_type: 'boolean',
            prefix: 'chart_of_account',
          },
          search_config: {},
          export_config: {},
          import_config: {},
          field_name: 'status',
          inheritance_config: {
            value: 'status.capitalize',
          },
        },
        {
          field_type: 'text',
          display_name: 'Created By',
          primary_key: false,
          required: false,
          workflow: false,
          filter: true,
          search: false,
          export: true,
          import: false,
          inheritance: false,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            filter_field_type: 'text',
            prefix: 'chart_of_account',
          },
          search_config: {},
          export_config: {},
          import_config: {},
          field_name: 'created_by',
        },
        {
          field_type: 'text',
          display_name: 'Updated By',
          primary_key: false,
          required: false,
          workflow: false,
          filter: true,
          search: false,
          export: true,
          import: false,
          inheritance: false,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            filter_field_type: 'text',
            prefix: 'chart_of_account',
          },
          search_config: {},
          export_config: {},
          import_config: {},
          field_name: 'updated_by',
        },
        {
          field_type: 'date',
          display_name: 'Created Date',
          primary_key: false,
          required: false,
          workflow: false,
          filter: true,
          search: false,
          export: true,
          import: false,
          inheritance: false,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            prefix: 'customer',
            filter_field_type: 'date',
          },
          search_config: {},
          export_config: {},
          import_config: {
            sample_value: '12/20/2020',
          },
          field_name: 'created_date',
        },
        {
          field_type: 'date',
          display_name: 'Updated Date',
          primary_key: false,
          required: false,
          workflow: false,
          filter: true,
          search: false,
          export: true,
          import: false,
          inheritance: false,
          description: '',
          tooltip: '',
          formatter: '',
          allowed_values: [],
          validations: {},
          filter_config: {
            prefix: 'customer',
            filter_field_type: 'date',
          },
          search_config: {},
          export_config: {},
          import_config: {
            sample_value: '12/20/2020',
          },
          field_name: 'updated_date',
        },
      ],
      actions: {
        create: {
          workflow: true,
          label: 'Create Record',
        },
        edit: {
          workflow: true,
          label: 'Update Record',
        },
        remove: {
          workflow: false,
          label: 'Delete Record',
        },
      },
      associations: ['account_type', 'user'],
      version: 1,
      is_auto_check: false,
      description: '',
      filter_associations: ['chart_of_account'],
    },
  },
};

describe('findByAttributes', () => {
  describe('getAllMetadataFields', () => {
    it('should return order of tables', async () => {
      axios.post = jest.fn().mockResolvedValue(metadata);

      const names = await getTablesOrder(
        ['chart_of_account', 'account_type'],
        {} as users,
        {} as companies,
      );

      expect(names.map((n) => Object.keys(n)[0])).toEqual([
        'account_type',
        'chart_of_account',
      ]);
    });
    it('should return error and empty array', async () => {
      axios.post = jest.fn().mockResolvedValue(undefined);

      const names = await getTablesOrder(
        ['chart_of_account', 'account_type'],
        {} as users,
        {} as companies,
      );

      expect(names.map((n) => Object.keys(n)[0])).toEqual([
        'chart_of_account',
        'account_type',
      ]);
    });
  });
});
